id: A7DEACA45
base_file: f79F8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:54:52.549391
  last_modified_at: 2022-05-30 18:54:52.549400
